### ISSUE TITLE
getting error trying to run the tests.

### ISSUE THREAD

**Issue by meltinglava** [Arxcis/adventofcode2018#28]
running any of the npm commands i get:
```
> ava --verbose


  ✖ Couldn't find any files to test

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adventofcode2018@ all: `ava --verbose`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the adventofcode2018@ all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by meltinglava** [comment]
and node generate returns
```
let dayDirs = files.filter(file => file.isDirectory())
                                        ^

TypeError: file.isDirectory is not a function
    at files.filter.file (/home/ros/projects/adventofcode2018/generate.js:10:41)
    at Array.filter (<anonymous>)
    at Object.<anonymous> (/home/ros/projects/adventofcode2018/generate.js:10:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
```

**Comment by Arxcis** [comment]
Oh no! What is your node version? 

Here is mine
```
$ node -v
v11.3.0

$ npm -v
6.4.1
```

If on linux to get the latest node-version install `nvm` (https://github.com/creationix/nvm)
```
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
```
Restart terminal and then run
```
nvm install node
```

**Comment by meltinglava** [comment]
Old version of node was the problem. Should probably put this in the readme

**Comment by Arxcis** [comment]
> Old version of node was the problem. Should probably put this in the readme

Ok good you figured it out. I have updated README.md info about Node version 👍
